apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-auditor
  namespace: cka-ca-q002
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kpl-node-reader
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get","list","watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kpl-node-reader
subjects:
  - kind: ServiceAccount
    name: node-auditor
    namespace: cka-ca-q002
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kpl-node-reader
