apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
kubernetesVersion: v1.35.8
controlPlaneEndpoint: one-control-plane.invalid:6443
networking:
  podSubnet: 10.200.0.0/16
  serviceSubnet: 10.200.0.0/12
etcd:
  external:
    endpoints:
      - https://127.0.0.1:12379
    caFile: /tmp/invalid-ca.crt
    certFile: /tmp/invalid-client.crt
    keyFile: /tmp/invalid-client.key
